# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52b30902cf4b86ce816a3316130a00c24ac14ec049cf1f88bd05e586dac900a4df8340bb42c5213b0e6a41efc87c7eb7be5853930f09097acba419c3f294d581

test:
  secret_key_base: 9966990136db052ec7efd0440c8f9dd064b59d44fdab5c8a428bc0c626033e57d95ad711f3f86f49108c6789acb78c5007f2b6714dd422386759ce82508883d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
